USE [master]
GO

/****** Object:  Database [dbExcel]    Script Date: 18.8.2017 19:41:29 ******/
CREATE DATABASE [dbExcel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Deneme', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Deneme.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Deneme_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Deneme_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbExcel] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbExcel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbExcel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbExcel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbExcel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbExcel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbExcel] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbExcel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbExcel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbExcel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbExcel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbExcel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbExcel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbExcel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbExcel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbExcel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbExcel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbExcel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbExcel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbExcel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbExcel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbExcel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbExcel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbExcel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbExcel] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbExcel] SET  MULTI_USER 
GO

ALTER DATABASE [dbExcel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbExcel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbExcel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbExcel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbExcel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbExcel] SET  READ_WRITE 
GO

